<?php foreach ($this->view->Contacts as $key => $contact) { ?>
    <div id="Contact">
        <div id="Name">
            <label><strong>Name:</strong></label> <?= $contact['name'] ?>
        </div>
        <div id="Number">
            <label><strong>Number:</strong></label> <?= $contact['number'] ?>
        </div>
        <div id="Email">
            <label><strong>Email:</strong></label> <?= $contact['email'] ?>
        </div>
    </div>
<?php } ?>
