<form>
    <div class="form-group">
        <label for="formGroupExampleInput"><strong>Name:</strong></label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2"><strong>Number:</strong></label>
        <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Number of phone">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2"><strong>Email:</strong></label>
        <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Person email">
    </div>
    <div>
    <button class="btn btn-button bg-success text-white" style="width: 100%;">Register</button>
    </div> 
</form>